# Configuration file
# Example for a population study
#
# This file contains the steering parameters of SoHAPPy.
# In YAML, True and False are equivalent to python, whereas the python None is coded as Null

#=============================================================================#
# The following parameter values can be superseded by the command line
# dbg:
#   if negative or zero : no plot
#   0: evt counting, 1: + some results, 2: + event details
#   3: details for each trials
# ifirst : either an id to start with, or a list (then ngrb is useless)
#  e.g. ifirst=1 
#       ifirst=[1,2,3] 
#       ifirst =[751, "090902B","080916C","130427A"]
#-----------------------------------------------------------------------------#
ifirst          : [343, 980, 465, 676, 785]  # integer, first source. Can be a list, e.g. [12, "190829A"]
ngrb            : 1     # integer, number of source to be read - if 1 specific actions on one grb
# res_dir         : "../output/test"   # The output folder
res_dir         : "D:/000_Today/SoHAPPy_tests"   # The output folder
niter           : 1          # Number of Monte Carlo trials
dbg             : 2            # From 0 to 3, increasingly verbosy
#=============================================================================#
# output files
#-----------------------------------------------------------------------------#
datafile        : "data.txt"    # Population main output file
logfile         : "analysis.log" # Text file with results, status and warnings 
save_simu       : True         # Simulation saved to file for offline use
save_grb        : False         # GRB class saved to disk -> use grb.py main
remove_tarred   : False         # Remove tarred files, otherwise keep for faster access
#=============================================================================#
# Simulation 
# Possible EBL models are from gammapy. Use "built-in" for the absorbed data 
# in the input file (if any)
#-----------------------------------------------------------------------------#
seed            : 2021          # Choose ‘random-seed’ to randomize
do_fluctuate    : False         # Statistical fluctuations are enabled
do_accelerate   : False          # When True, the simulation is stopped if
                                # none of the first trials in the limit
                                # of 1 - det_level have reached the minimal
                                #significance (3 sigma).
# EBLmodel        : "in-file"   # Extragalactic Background Light model 
# EBLmodel        : "gilmore"   # Extragalactic Background Light model 
EBLmodel        : "dominguez"   # Extragalactic Background Light model 
observatory     : "CTA"
#array_North     : "FullArray"   # IRF subarrays in North (FullArray, MST...)
#array_South     : "FullArray"   # IRF subarrays in South (FullArray, MST...)
array_North     : "4LSTs09MSTs"   # IRF subarrays in North (FullArray, MST...)
array_South     : "4LSTs14MSTs40SSTs"   # IRF subarrays in South (FullArray, MST...)
#=============================================================================#
# Visibility 
# 
# The absolute maximum repointing times for the CTA telescopes (to and from
# anywhere in the observable sky) will be 50 s for the LSTs and 90 s for the
# MSTs and SSTs, with the goal to reach shorter slewing times
# (Ref. CTA Science document).
#
# Choose the slewing times, related to tye subarrays
#   dtslew_North = " 0 s" # No delay
#   dtslew_South = "60 s" # Typical MST delays
#
# Parameters
# Normal conditions (compromise):
# altmin    : "24 deg"    # CTA requirement horizon
# altmoon   : "-0.25 deg" # Moon above horizon
# moondist  : "30  deg"   # Acceptable Moon distance
# moonlight :  0.6        # Acceptable Moon brightness
 
# To maximise the visibility use the following values:
#  altmin    :  0  deg   # Ensure that the source is always above horizon
#  altmoon   :  90 deg   # Ensure that the moon never vetoes the visibility
#  moondist  :  0  deg   # The Moon distance do not veto the visibility
#  moonlight :  1.0      # The Moon brightness is not a limitation

# To minimize the visibility (i.e. veto as soon as the moon is above horizon)
altmin    :  24 deg   # Ensure that the source is always above horizon
altmoon   : -0.25 deg # Moon above horizon
moondist  : 180 deg   # The Moon vetoes even if far away
moonlight :  0.0      # The Moon vetoes even if new Moon

#-----------------------------------------------------------------------------#
depth           : 3             # Max. number of nights
skip            : 0             # Number of first nights to be skipp

dtslew_North    : "30 s"
#dtslew_South    : "30 s"        # Maximum slewing time delay
dtslew_South    : "30 s"        # Maximum slewing time delay
fixslew         : True          # If False generate a random delay < dtslew
dtswift         : "77 s"        # Fixed SWIFT latency
fixswift        : True          # If False, the latency is generated from real data file (see below)
swiftfile       : "../input/swift/Swift_delay_times.txt" # Swift latency file
vis_cmp         : False          # If True, visibility is computed on the fly
vis_dir         : ../input/visibility/vis_24_strictmoonveto  # If defined, visibility instances are read from folder
#vis_dir         : Null
#=============================================================================#
# input folders
#-----------------------------------------------------------------------------#
grb_dir         : "../input/lightcurves/"   # Folder hosting the GRB files
#irf_dir         : "D:/CTA/00-Data/IRF-SoHAPPy/prod3-v2" # IRF folder (specific subfolder organisation)
irf_dir         : "D:/CTA/00-Data/IRF-SoHAPPy/prod5-v0.1" # IRF folder (specific subfolder organisation)
# irf_dir    = "../input/irf/Full/prod3-v2"
# irf_dir    = "../input/irf/Full/prod5-v1" 
#=============================================================================#
# These parameters are intended to be modified by experts only
#-----------------------------------------------------------------------------#
method          : 0             # Not used (detection method)
obs_point       : "end"         # Observation position in the time slice
test_prompt     : False         # If True test prompt alone (experimental)
use_afterglow   : False         # Prompt characteristics from the afterglow with same id.
signal_to_zero  : False         # Keep only background, set signal to zero
fixed_zenith    : Null          # If a value ("20 deg") freezes zenith in IRF
magnify         : 1             # Multiplicative factor of the input flux, for tests (0 forbidden)
silent          : False         # If True, nothing on screen (output to log)
write_slices    : False         # Store detailed information on slices if True
save_dataset    : False         # Not implemented (save datasets)
forced_visible  : False         # If True, forced to be visible at fixed_zenith