# Configuration file
#
# This file contains the steering parameters of SoHAPPy.
# In YAML, True and False are equivalent to python, whereas the python None 
# is coded as Null

#=============================================================================#
# The following parameter values can be superseded by the command line
# dbg:
#   if negative or zero : no plot
#   0: evt counting, 1: + some results, 2: + event details
#   3: details for each trials
# ifirst : either an id to start with, or a list (then ngrb is useless)
#  e.g. ifirst=1 
#       ifirst=[1,2,3] 
#       ifirst =[751, "090902B","080916C","130427A"]
#-----------------------------------------------------------------------------#

# ifirst : [275, 283, 441] #, 758, 874, 945, 964] # Detected for SHORT at 107 s
ifirst : [758, 874, 945, 964] # Detected for SHORT at 107 s
# ifirst        : 1   # integer, first source. Can be a list, e.g. [12, "190829A"]
ngrb            : 1   # integer, number of source to be read - if 1 specific actions on one grb
niter           : 100   # Number of Monte Carlo trials
dbg             : 1   # From 0 to 3, increasingly talkative
res_dir         : "D:/000_Today/SoHAPPy_tests/short"   # The output folder
# grb_dir         : "D:/CTAA/SoHAPPy/input/lightcurves/LONG_FITS/"   # Folder hosting the GRB files
grb_dir         : "D:/CTAA/SoHAPPy/input/lightcurves/SHORT_FITS/"   # Folder hosting the GRB files
# grb_dir         : "../input/lightcurves/LONG_FITS/"   # Folder hosting the GRB files
save_simu       : False         # Simulation saved to file for offline use
save_grb        : False         # GRB class saved to disk -> use grb.py main


#=============================================================================#
# Simulation 
# Possible EBL models are from gammapy or gilmore data on disk. 
# Use "built-in" for the absorbed data in the input file (if any)
#-----------------------------------------------------------------------------#
EBLmodel        : "dominguez"   # Extragalactic Background Light model 
prompt          : False          # If True getdata from disk if they exist

array_North     : "FullArray"   # IRF subarrays in North (FullArray, MST...)
dtslew_North    : "30 s"        # Maximum slewing time delay
# dtslew_North    : "0 s"        # Maximum slewing time delay
array_South     : "FullArray"   # IRF subarrays in South (FullArray, MST...)
dtslew_South    : "30 s"        # Maximum slewing time delay
# dtslew_South    : "0 s"        # Maximum slewing time delay
fixslew         : True          # If False generate a random delay < dtslew

dtswift         : "77 s"        # Fixed SWIFT latency
fixswift        : True          # If False, latency generated from Swift data 
swiftfile       : "../input/swift/Swift_delay_times.txt" # Swift latency file

# IRF folder (specific subfolder organisation)
irf_dir         : "D:/CTAA/SoHAPPy/input/irf/Full/prod3-v2" 
# irf_dir    = "../input/irf/Full/prod3-v2"
# irf_dir    = "../input/irf/Full/prod5-v1"

seed            : 2021          # Choose ‘random-seed’ to randomize
do_fluctuate    : True          # Statistical fluctuations are enabled
do_accelerate   : True         # When True, the simulation is stopped if
                                # none of the first trials in the limit
                                # of 1 - det_level have reached the minimal
                                #significance (3 sigma).
# Visibility can be read from disk (folder is given), 
# from the GRB input files (Null) or recomputed with parameters defined in 
# visibility.yaml                                
# visibility      : "D:/CTAA/SoHAPPy/input/visibility/long/vis_24_strictmoonveto"  
visibility      : "D:/CTAA/SoHAPPy/input/visibility/short/vis_24_strictmoonveto"  
# visibility      : "D:/CTAA/SoHAPPy/input/visibility/short/vis_24_nomoonveto"  
# visibility      : Null
# visibility      : "strictmoonveto"
# visibility      : "nomoonveto"

#=============================================================================#
# output files
#-----------------------------------------------------------------------------#
datafile        : "data.txt"    # Population main output file
logfile         : "analysis.log" # Text file with results, status and warnings 
remove_tarred   : False # Remove tarred files, otherwise keep for faster access
  
#=============================================================================#
# These parameters are intended to be modified by experts only
#-----------------------------------------------------------------------------#
method          : 0      # Not used (detection method)
obs_point       : "end"  # Observation position in the time slice
test_prompt     : False  # If True test prompt alone (experimental)
use_afterglow   : False  # Prompt characteristics from the afterglow with same id.
signal_to_zero  : False  # Keep only background, set signal to zero
fixed_zenith    : Null   # If a value ("20 deg") freezes zenith in IRF
magnify         : 1      # Multiplicative factor of the input flux, for tests
silent          : False  # If True, nothing on screen (output to log)
write_slices    : False  # Store detailed information on slices if True
save_dataset    : False  # Not implemented (save datasets)
forced_visible  : False  # If True, the GRB is always visible (infinite nights)
n_night         : Null   # Limit GRB data to a maximal number of nights
Emax            : Null   # Limit GRB data energy bins to Emax